name = "tannerwj-com"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Static assets configuration
[assets]
directory = "public"
binding = "ASSETS"

# Environment variables
[vars]
NODE_ENV = "production"

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect rules
[[redirects]]
  from = "/home"
  to = "/"
  status = 301
